import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { StorefrontProvider } from "@/contexts/storefront";
import { headers } from "next/headers";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Storefront",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const publicKey = headers().get("bb-api-key") as string;
  console.log("publicKey", publicKey);
  const typesRes = await fetch("http://localhost:3001/api/storefront/types", {
    headers: {
      "x-public-key": publicKey,
      Accept: "application/json",
    },
  });
  const types = await typesRes.json();
  const categoriesRes = await fetch(
    "http://localhost:3001/api/storefront/categories",
    {
      headers: {
        "x-public-key": publicKey || "",
        Accept: "application/json",
      },
    }
  );
  const categories = await categoriesRes.json();
  console.log("categories", categories);

  return (
    <html lang="en" className={inter.className}>
      <body>
        <Suspense fallback={<p>Loading...</p>}>
          <StorefrontProvider>
            <Navbar types={types} />

            <main>{children}</main>
          </StorefrontProvider>
        </Suspense>
      </body>
    </html>
  );
}
